### ISSUE TITLE
Discord usernames are not unique

### ISSUE THREAD

**Issue by aeruhxi** [dev-circle-np/dev-circle-np.github.io#31]
We should use full discord username (along with discriminator). For example, `AbsoluteZero#0296` instead of `AbsoluteZero`.

**Comment by amitness** [comment]
@rameshsyn

**Comment by coderpradp** [comment]
@bibek94 Did you change discord's username because I can't find you?
@rameshsyn And do we manually enter the discriminator or is there any way around?

**Comment by aeruhxi** [comment]
@coderpradp You should manually enter the discriminator of yours since the username of yours without the discriminator attached is not unique.

**Comment by coderpradp** [comment]
So shall I update the username of all or respective user will be sending their own PR?

**Comment by axispx** [comment]
@coderpradp sure
