### ISSUE TITLE
Set background for Motto section

### ISSUE THREAD

**Issue by amitness** [dev-circle-np/dev-circle-np.github.io#35]
Use a background image for the "Grow along with helping others" div. The image could be something related to Nepal: temple, nature etc.

**Comment by axispx** [comment]
https://github.com/dev-circle-np/dev-circle-np.github.io/commit/b05e3ce5ea4a1e45ca0c6705fa3dfb2116c3e005 fixes this issue.

**Comment by amitness** [comment]
@anarchyrucks A small trick. You can close a issue using a commit message as well. Just structure the commit message as "Fixes #issueno.: Change background image bla bla". Resolves can also be used instead of Fixes.

**Comment by axispx** [comment]
Thanks. I knew it the hard way. 😥
