### ISSUE TITLE
Redesigning the members page

### ISSUE THREAD

**Issue by amitness** [dev-circle-np/dev-circle-np.github.io#37]
I was thinking of redesigning the members page using card UI layout. How does this look?

![screencapture-dev-circle-np-github-io-members-1493121064139](https://cloud.githubusercontent.com/assets/8587189/25383958/ffb4d45e-29dd-11e7-8733-5615272d2958.png)

If it's OK, I'll proceed.

**Comment by amitness** [comment]
- Use 2px border radius

**Comment by rameshsyn** [comment]
@studenton It's looks ok for me. :ship:  :+1: 
@AbsoluteZero273  @anarchyrucks  What do you say ?

**Comment by axispx** [comment]
Looks great. Can you think of a good colour scheme too while you are at it? 😃

**Comment by amitness** [comment]
@anarchyrucks I was playing around with material design colors. I'll see what I can come up with.

Referring: http://flatuicolors.com/ and https://material.io/guidelines/style/color.html. See if you like something there.

Current site color blue and grey looks a bit dull.

**Comment by aeruhxi** [comment]
Yeah, everything looks nice except that the color seems a bit off.

**Comment by amitness** [comment]
@AbsoluteZero273 The background grey?

**Comment by aeruhxi** [comment]
yeah, probably that. I am not a color expert. So I really don't know what color looks good without hit and trial. :sweat_smile:

**Comment by amitness** [comment]
Same here. I play around with the chrome developer tools and check what looks good.

**Comment by rameshsyn** [comment]
Same here :joy:
