### ISSUE TITLE
Build showcase page

### ISSUE THREAD

**Issue by amitness** [dev-circle-np/dev-circle-np.github.io#39]
https://dev-circle-np.github.io/showcase/

**Comment by rameshsyn** [comment]
@studenton Bro, Any advice on projects showcase ? 
Initially, I was thinking to put group DCN projects and DCN members projects in showcase.

**Comment by amitness** [comment]
How about just redirecting to this: https://github.com/dev-circle-np?utf8=%E2%9C%93&q=&type=public

**Comment by rameshsyn** [comment]
@studenton Ok, that would be great.

**Comment by axispx** [comment]
@studenton @rameshsyn we can put the link in the navbar and open in new tab
